# Project JEJU Configuration

# 기본 설정
seed: 42
data_path: "/content/drive/MyDrive/Project_JEJU/dataset"
embeddings_path: "/content/drive/MyDrive/Project_JEJU/modeling/embeddings_pkl"
output_path: "/content/drive/MyDrive/Project_JEJU/models/0412"

# 모델 아키텍처
model:
  num_pc_dims: 7
  hidden_dim: 256
  num_heads: 4
  persona_expansion_factor: 2
  emotion_embedding_dim: 128
  dropout_rate: 0.25

# 학습 설정
training:
  num_epochs: 30
  batch_size: 128
  learning_rate: 0.0003
  weight_decay: 0.0002

# 대조학습 설정
contrastive:
  internal_weight: 0.3
  external_weight: 0.7
  temperature: 0.5

# 손실 함수 가중치
loss_weights:
  mse: 0.5
  bpr: 0.3
  reg: 0.1
  filter_reg: 0.1

# 평가 설정
evaluation:
  top_k_values: [5, 10]
  min_visits: 5
  n_splits: 3
